### ISSUE TITLE
RS 005: Implementar algoritmo de busqueda de texto

### ISSUE THREAD

**Issue by Tewi** [Hawkline451/TeraCity#12]
Implementar algoritmo de busqueda de textual, para poder buscar cada ocurrencia en el codigo. 
El algoritmo debe iterar en cada archivo  y retornar una lista de ocurrencias, de la siguiente manera:

List<file, index> = searchText(text, files)

Luego con la lista se marcan los bloques adecuados del edificio correpondiente en la ciudad, en aquellos en donde se encuentra el texto buscado.

Implementar algoritmo a mano o posiblemente usar una libreria como Lucene que ya tiene el algoritmo imlementado y solamente usar un adapter.

**Comment by SimonRBG** [comment]
### Initiation:

Searching text (strings) into the code and highlight the corresponding blocks.

**Comment by SimonRBG** [comment]
### Concept location :

searching, text, code, highlight, blocks
**Class**  FlyMode.SearchCommands.java  - **Method** searchText   - **Method** putHighlightBlockAt (Find with Ctrl+H search on Eclipse "searchText", "higlight" and "block"). 
**Algorithm already exitsing, but not entirely working (now have to put the textures on corresponding blocks).**

**Comment by SimonRBG** [comment]
## Impact Analysis:
