### ISSUE TITLE
RS 003 : Reemplazar los bloques puestos fuera los edificios por otro.

### ISSUE THREAD

**Issue by pbadillatorrealba** [Hawkline451/TeraCity#13]
Buscar algún tipo de bloque que sea transparente y reemplazar los generados en el paso anterior.

**Comment by camilo-zenteno** [comment]
### Initiation
- Replace an specific block for another.

**Comment by camilo-zenteno** [comment]
Inicialización

Reemplazar un bloque específico, por otro que sea transparente.

**Comment by camilo-zenteno** [comment]
Inicialización

Reemplazar un bloque específico, por otro que sea transparente.

**Comment by camilo-zenteno** [comment]
Inicialización

Reemplazar un bloque específico, por otro que sea transparente.

**Comment by camilo-zenteno** [comment]
### Concept Location
- Block
- **Class** - **Method**
