### ISSUE TITLE
RS 010: Input de texto para la busqueda

### ISSUE THREAD

**Issue by Tewi** [Hawkline451/TeraCity#14]
Implementar metodo para hacer la busqueda de texto, hace una o las dos siguientes opciones:
- Implementar comando en la consola de TeraCity (i.e. search "Main").
- Agregar en el menu de juego la opción de busqueda de texto, en donde tenga un field de texto en donde se puede hacer el input del texto a buscar.

**Comment by pbadillatorrealba** [comment]
**Initiation** :
- Implement a command in the Teracity console that reads a string and then finds it on the city.

**Comment by pbadillatorrealba** [comment]
**Concept Location** :
- Console
- String
- Read
- Search

This concepts were found in the package FlyMode using a dependency search. Also, I realized that this software requirement were previously implemented but it's not functional.

**Comment by pbadillatorrealba** [comment]
Análisis de Impacto

**Comment by DemianDrake** [comment]
## Important files

/engine/src/main/resources/assets/ui/ingame/search/searchMenuScreen.ui
Search Menu appearance, coded in json.

/engine/src/main/java/org/terasology/rendering/nui/layers/search/SearchMenuScreen.java
Search menu manager and controller.
