### ISSUE TITLE
RS 001 : Separar los edificios a una distancia suficiente 

### ISSUE THREAD

**Issue by pbadillatorrealba** [Hawkline451/TeraCity#15]
Se observó en el juego que hay edificios con solo un bloque de separación, por lo que para avanzar al siguiente paso (colocar una capa de bloques exterior a los edificios) hay que separarlos a una distancia que lo permita.
Para esto, hay que entrar en el código donde se generan los edificios y modificarlo.

**Comment by pbadillatorrealba** [comment]
### Initiation :
- Each building need a minimum separation of atleast 3 blocks.

**Comment by pbadillatorrealba** [comment]
Concept Location : 
- Minimum Separation, Blocks, Building
- **Class** - **Method**

**Comment by rodrigoveraa** [comment]
### Concept Location

_Minimum Separation_ was not found, so search was expanded to include terms like _place_, _position_, and such. After performing a text search on _position_, the most relevant result is the following:
- WorldCodeCity --> org.terasology.codecity.world.map.CodeMapHash - canPlaceInPosition

**Comment by rodrigoveraa** [comment]
### Impact Analysis
