### ISSUE TITLE
RS 006: Implementar la obtención de log de commits

### ISSUE THREAD

**Issue by SimonRBG** [Hawkline451/TeraCity#16]
Implementar método que obtenga el log de los commits para extraer información de commit previos, junto al respectivo autor y fecha.

**Comment by Hawkline451** [comment]
### Initiation:

Extract commit information from GitHub logs .

**Comment by Hawkline451** [comment]
### Concept Location:

Extract, Log, Commit.
**Class** GitMetrics - **Method**
