### ISSUE TITLE
RS 007: API de bloques

### ISSUE THREAD

**Issue by Tewi** [Hawkline451/TeraCity#17]
Crear una API para colorear las caras de los edificios segun un analisis sobre el codigo del edifico.

**Comment by Tewi** [comment]
**Initiation**
Create an application interface for the coloring specific blocks related to code sections in the buildings, as an answer for a query about the code.

**Comment by Tewi** [comment]
**Concept Location**
Create, API, blocks, coloring, query

**Comment by cpmeneses** [comment]
**Localización de Concepto:**
La API debe ser capaz de guardar:
- La query de busqueda con la que se quiere pintar.
- Que bloques representan que información. (ej: Bloques rojos donde hayan bugs)
La API debe recibir:
- El algoritmo de pintado, el cual debe entregar que información está relacionada a cada bloque del muro de vidrio. (ej: Si en un bloque hay lineas con bugs)
- Un arreglo de los bloques de vidrio del muro de vidrio. O algún objeto que le permita cambiar el  color de estos de manera ordenada.
Con estos dos últimos, mas la información guardada en la API, se puede pintar el muro, aplicando el algoritmo en los muros.

**Comment by cpmeneses** [comment]
**Analisis de Impacto:**
Esta clase debe interactuar con la clase que genera el mapa y la clase que ubica los bloques.
