### ISSUE TITLE
Comandos en castellano parcial o total

### ISSUE THREAD

**Issue by DemianDrake** [Hawkline451/TeraCity#21]
Dejar todos los comandos apropiadamente en inglés, pues algunos se encuentran en castellano parcial o totalmente.
- CoberturaAnalysis.
- applyColoring.
- updateColoringState
- paintWithGit
- showParse
- paintWithCheckStyle
- paintWithCobertura
- **Agregar màs si otras...**

**Comment by SimonRBG** [comment]
- [x]  CoberturaAnalysis.
- [x] applyColoring.
- [x] updateColoringState
- [x] paintWithGit
- [x] showParse
- [x] paintWithCheckStyle
- [x] paintWithCobertura
