### ISSUE TITLE
RS 004 : Interfaz general para seleccionar la métrica

### ISSUE THREAD

**Issue by pbadillatorrealba** [Hawkline451/TeraCity#22]
Se necesita implementar una interfaz dentro del juego que permita cambiar entre las métricas que serán visualizadas. 
Hay dos opciones :
- Agregar la interfaz dentro del juego (con botones y otros) 
- Agregar los comandos a la consola.

**Comment by AlbertoSara** [comment]
## Initiation

Create a graphical interface to select the metrics that will be displayed.

**Comment by AlbertoSara** [comment]
## Concept Location

Create, graphical interface, metrics.

**Comment by Hawkline451** [comment]
Interfaz PMD, GitHub y Findugs funcionando correctamente
