### ISSUE TITLE
RS 013: Ejecución de PMD

### ISSUE THREAD

**Issue by SimonRBG** [Hawkline451/TeraCity#23]
Implementar un metodo que ejecuta PMD y obtiene los code Smells generados.

**Comment by AlbertoSara** [comment]
## Initiation
Implement method to obtain code smells through PMD.

**Comment by AlbertoSara** [comment]
## Concept Location

Code smells, PMD, method.

**Relevant classes:**
PMDCommand.java
PMDProcessor.java

**Comment by AlbertoSara** [comment]
Method to execute PMD already existed (pmdColoring command in PMDCommand.java) but it didn't create the thread ThreadPMDExecution properly. This has been fixed and now it uses the related jar files to find errors.

**Comment by AlbertoSara** [comment]
Unnecessary files removed.

**Comment by AlbertoSara** [comment]
Additional methods to handle the results of the analysis will be added. Results will be stored in a TSV file, with the first column being the name of the file, and the following ones being the number of the detected lines.

**Comment by AlbertoSara** [comment]
Issue finished succesfully, branch merged to master.
