### ISSUE TITLE
RS 014: Resaltar los code Smells.

### ISSUE THREAD

**Issue by SimonRBG** [Hawkline451/TeraCity#24]
Encontrar las lineas que presentan code Smells dentro TeraCity y resaltarlas agregando bloques semi-transparentes.

**Comment by SimonRBG** [comment]
## Initiation:
Highlight the considerated lines on blocks using the coloring API.

**Comment by SimonRBG** [comment]
## Concept Location:
_Highlight, lines, blocks, coloring API._

**Comment by SimonRBG** [comment]
## Impact Analysis:
Adding command findBugsColoring in GitMetrics (contains command to color using engines based on tsv files).

**Comment by SimonRBG** [comment]
PMD done? Can we close?

**Comment by Hawkline451** [comment]
PMD done
