### ISSUE TITLE
RS 015: Reemplazo o construccion eficiente de edificios independientes

### ISSUE THREAD

**Issue by Tewi** [Hawkline451/TeraCity#26]
Implementar la creacion o actualizacion de edificios por separado. Actualmente no es posible generar un edificio solamente sin destruirlo por completo o sin destruir la cuidad.

**Comment by Hawkline451** [comment]
Cada edificio contiene murallas independientes que puedes ser modificadas o limpiadas con comandos desde la consola ingame.
