### ISSUE TITLE
RS 016: Bloques transparentes

### ISSUE THREAD

**Issue by DemianDrake** [Hawkline451/TeraCity#27]
Crear bloques transparentes.

**Comment by miguelo49** [comment]
RU 007: Enfocar edificios según un filtro, haciendo el resto semi-transparente.

**Comment by miguelo49** [comment]
## Initiation :
- Create a transparent texture

**Comment by miguelo49** [comment]
## Locacion de Conceptos:

Existen bloques de hielo y vidrio los cuales tienen un parámetro de transparencia, estos pueden convertirse facilmente en bloques transparentes
