### ISSUE TITLE
RU 002: Busqueda textual de codigo

### ISSUE THREAD

**Issue by Tewi** [Hawkline451/TeraCity#3]
- **Descripcion:** Debe poder realizarse una búsqueda de texto en el código, resaltando los lugares en donde se encuentran coincidencias en la ciudad.
- **Fuente:** Cliente
- **Prioridad:** Critica
- **Estabilidad:** Intransable
- **Fecha de Actualización:** 2016-11-3
- **Incremento:** 0
- **Tipo:** Funcional
- **T. de Usuario asociado:** Jugador

**Requisitos de software asociados:**
#14 #12 #22

**Comment by Tewi** [comment]
**Concept Location**

**Comment by Tewi** [comment]
**Analisis de Impacto**

**Comment by Hawkline451** [comment]
Done
