### ISSUE TITLE
RU 005 : Modificar edificios sin destruir la ciudad. 

### ISSUE THREAD

**Issue by pbadillatorrealba** [Hawkline451/TeraCity#5]
- **Descripcion:** Agregar la característica de remplazar un edificio o parte de este sin destruirlo o destruir toda la ciudad sin que esto degrade el rendimiento.
- **Fuente:** Cliente
- **Prioridad:** Critica
- **Estabilidad:** Intransable
- **Fecha de Actualización:** 2016-11-3
- **Incremento:** 0
- **Tipo:** Calidad
- **T. de Usuario asociado:** Jugador

**Requisitos de software asociados:**
#26

**Comment by Hawkline451** [comment]
Done!
