### ISSUE TITLE
RU 006 : Utilizar dos caras para mostrar el codigo y dos caras para mostrar las metricas

### ISSUE THREAD

**Issue by pbadillatorrealba** [Hawkline451/TeraCity#7]
- **Descripcion:** Se pide que los edificios se generen de tal forma que en dos de sus caras se muestre el codigo y en las otras dos se muestren las métricas relacionadas con el código.
- **Fuente:** Cliente
- **Prioridad:** Deseable
- **Estabilidad:** Transable
- **Fecha de Actualización:** 2016-11-3
- **Incremento:** 0
- **Tipo:** Restricción
- **T. de Usuario asociado:** Jugador

**Comment by Hawkline451** [comment]
Done!
